version: '3.8'

services:
  postgres-test:
    image: 'postgres:10.7'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - 5433:5432
  redis:
    image: 'redis:latest'
    ports:
      - 6380:6379
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
